### PR TITLE
signup-button-added

### PR DESCRIPTION
**Pull request by sahil-arsss**
A signup button has been added to the main navigation bar

solved issue  #249 

image

### CODE REVIEW

**Comment by jaiyankargupta** [comment]
@sahil-arsss signup button, darkmode se just pahle hona chhaiye tha, and botton ka text signup nhi, get started hona chahiye

**Comment by jaiyankargupta** [comment]
Screenshot 2024-07-22 at 3 26 12 PM

**Comment by sahil-arsss** [comment]
Okay sir

**Comment by jaiyankargupta** [comment]
@sahil-arsss ??

**Pull request closed without merging**
